# capsule version
version = "0.10.0"
# path of deployment config file
deployment = "deployment.toml"

[rust]
workspace_dir = "contracts"

[[contracts]]
name = "ckb-std-tests"
template_type = "Rust"

[[contracts]]
name = "exec-callee"
template_type = "Rust"
