name: Develop Rust

on:
  pull_request:
  push:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Deps
      run: |
        rustup target add riscv64imac-unknown-none-elf
    - name: Test
      run: |
        make
        make test
